### ISSUE TITLE
pdfjs: XXXXX.pdf is NOT public!

### ISSUE THREAD

**Issue by huntinux** [gkrid/dokuwiki-plugin-pdfjs#1]
When I preview the page, It shows me this warning "pdfjs: xxxxx.pdf is NOT public!"
and the result page show nothing.

how can I fix this problem? 
 thx

**Comment by solewniczak** [comment]
Give me more details. How exacly looks syntax you use? Which dokuwiki version do you use? If you can provide me printscreen with the result of plugin usage.

**Comment by huntinux** [comment]
dokuwiki version : Release 2016-06-26a "Elenor of Tsort"
nginx/1.10.1
Centos 7

http works fine, but https cannot show the content of the pdf.

screenshot for https
![](http://img.blog.csdn.net/20160929111150223)

screenshot for http
![这里写图片描述](http://img.blog.csdn.net/20160929110923845)

**Comment by solewniczak** [comment]
I cannot reproduce. Do you visit the same page using http and https? It may be problem with something else. Maybe some ACL issue.

**Comment by solewniczak** [comment]
Did you solve the problem?

**Comment by huntinux** [comment]
no.... I can't solve the problem. Maybe its my environment's problem...

**Comment by Curtingham** [comment]
I'm seeing the same problem. Here's the relevant details I can think of off the top of my head (I'll be happy to provide anything else that may help):

Operating system: Ubuntu 16.04, fully up-to-date
Dokuwiki version: Latest (Release 2017-02-19b "Frusterick Manners") - I had the same issue with the version 2017-02-19a, updated to see if it fixed. Issue is happening for both versions
PDFJS version: Latest  (2017-02-02) - Have uninstalled/reinstalled to see if it helped, so it's possible I previously had a different version, not sure though. I got the same results before/after
I can provide screenshots if necessary, but they would look just like the first screenshot provided by Huntinix. 

Description: PDFJS was working fine yesterday, while my Dokuwiki installation was http only. I then applied the steps from [This DigitalOcean Guide for setting up Apache self-signed cert](https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-apache-in-ubuntu-16-04), and now my site is running on https. After doing so, the issue described by huntinux started occurring (where there was a viewable/clickable PDF displayed before, now there's just a blank window. If doing edit, and then preview, I see the same "pdf-filename.pdf is NOT public!" message)

Without any changes to the .pdf, I'm able to open/view it fine with normal links to the PDF (I.E. not using the PDFJS plugin).

As a sanity check, I did a chmod 777 to the file itself - issue persists

I tried changing all users in ACL settings to have "delete" permissions, didn't resolve the issue

I actually see one different behavior from what Huntinix describes - After getting this site switched over to HTTPS, the HTTP site has the same problem - going back to the HTTP version of the site does not resolve the issue now

Edit: Forgot to put my syntax - This is what worked before I setup HTTPS just fine, and now produces this issue: {{pdfjs 100%,725px >:network-diagram.pdf}}

Thanks in advance for any advice!

**Comment by Curtingham** [comment]
As another sanity check, I fired up a Ubuntu VM (using Proxmox as the host platform), and was able to recreate the issue. I used a template, which is a very basic Ubuntu installation with nothing special to it.

I went through the standard installation procedure, and did nothing extra except upload a PDF, and install PDFJS. Works great in the HTTP version of the site.

After following the guide from my previous post to setup HTTPS, the issue occurs. This time, I get the same behavior as Huntinux - if I switch back to HTTP, the site works fine. If i visit HTTPS, it appears blank, unless I edit, and then I get the NOT public! message.

Hope this helps, let me know if I can provide any other details that would be useful.

Thanks again!

**Comment by solewniczak** [comment]
Thank you for exhaustive report. I'll try to fix it in the coming week. 
I glad to hear that you find my plugin useful :).

BR,
Szymon

W dniu 17.04.2017 o 08:47, MintyFresh pisze:

**Comment by solewniczak** [comment]
Check out your apache settings. In ` /etc/apache2/conf-enabled/ssl-params.conf` change the line: `Header always set X-Frame-Options DENY` to `Header always set X-Frame-Options SAMEORIGIN`. This fixes the issue on ubuntu.

**Comment by Curtingham** [comment]
> In /etc/apache2/conf-enabled/ssl-params.conf change the line: Header always set X-Frame-Options DENY to Header always set X-Frame-Options SAMEORIGIN

This worked like a charm. I see there was a recent update to the extension, so I also updated it before applying this. It seems like more of an operator error than an actual bug, if all that needed changed was that bit of the configuration.

Anyways, thank you so much for looking into this! Much happier to have my Dokuwiki running on SSL again, without having to give up the PDF viewer.
