### ISSUE TITLE
Warning in dokuwiki Release 2022-07-31a "Igor" using PDF.js

### ISSUE THREAD

**Issue by jeromeperez** [gkrid/dokuwiki-plugin-pdfjs#27]
When i try to use PDF-js i have these warning :

Warning: Undefined array key 1 in D:\xampp\htdocs\dokuwiki\lib\plugins\pdfjs\syntax.php on line 64

Warning: Undefined array key 1 in D:\xampp\htdocs\dokuwiki\lib\plugins\pdfjs\syntax.php on line 66

Warning: Undefined array key 1 in D:\xampp\htdocs\dokuwiki\lib\plugins\pdfjs\syntax.php on line 78

My pdf are are in a subfolder of media

**Comment by ParoTheParrot** [comment]
any news regarding Igor compatibility? @jeromeperez , @solewniczak

**Comment by jeromeperez** [comment]
Hi.
For the moment these warning have disapeared.
It's now OK
