### ISSUE TITLE
Viewer doesn't work since last update

### ISSUE THREAD

**Issue by siggi11** [gkrid/dokuwiki-plugin-pdfjs#3]
latest update (2017-02-02 (at Wed, 15 Feb 2017 09:00:22 +0100) installed throws

Uncaught TypeError: Cannot read property 'bind' of undefined
    at Object.secondaryToolbarInitialize [as initialize] (viewer.js:2218)
    at Object.pdfViewInitialize [as initialize] (viewer.js:6197)
    at HTMLDocument.webViewerLoad (viewer.js:7185)
secondaryToolbarInitialize @ viewer.js:2218
pdfViewInitialize @ viewer.js:6197
webViewerLoad @ viewer.js:7185

**Comment by solewniczak** [comment]
> latest update (2017-02-02 (at Wed, 15 Feb 2017 09:00:22 +0100) installed
> throws
>
> Uncaught TypeError: Cannot read property 'bind' of undefined
> at Object.secondaryToolbarInitialize [as initialize] (viewer.js:2218)
> at Object.pdfViewInitialize [as initialize] (viewer.js:6197)
> at HTMLDocument.webViewerLoad (viewer.js:7185)
> secondaryToolbarInitialize @ viewer.js:2218
> pdfViewInitialize @ viewer.js:6197
> webViewerLoad @ viewer.js:7185

What browser do you use? Can you send me PDF file that causes the 
problem? Do the previous version of plug-in works correctly with your 
file? Try to clean the browser cache (CTRL+SHIFT+R), it may help.

**Comment by siggi11** [comment]
*resolved* /  Thank you watching, 
but plugin just working proper since update the wiki to Release 2017-02-19 "Frusterick Manners".
(may be helped the new jquery).
*btw* THANKS A LOT for Disable upload button !!!
