### ISSUE TITLE
Specifying height in percent

### ISSUE THREAD

**Issue by jeLee6gi** [gkrid/dokuwiki-plugin-pdfjs#4]
When I specify height in percent the reader will always be around 150 px tall, no matter what number I put. Width on the other hand works fine in both percent and px.

My browser is Google Chrome Version 58.0.3029.96 (64-bit) on Linux. I run the latest build of dokuwiki and the pdfjs plugin.

Please let me know what information I can prodvide you with if you cannot reproduce the issue on your end.

**Comment by solewniczak** [comment]
It's how CSS works. What you exactly trying to achieve?

**Comment by jeLee6gi** [comment]
Well, I just wanted to manually adjust the height, can it only be done in px like in the examples on the plugin page?

**Comment by solewniczak** [comment]
Since web page height is infinite the height in percent usually doesn't make sense unless your container is in another container that has explicit height defined. You can use px, em or pt but percent may not work as you may except.

**Comment by jeLee6gi** [comment]
That makes a lot of sense, thanks for clearing that up!
