### ISSUE TITLE
Zoom level of viewer

### ISSUE THREAD

**Issue by BodoBiker** [gkrid/dokuwiki-plugin-pdfjs#5]
Hi,
I would like to define initial zoom level of the viewer. I use a PDF in landscape format. The automatic zoom seems to be orientated to the whole page. I would like to predefine zoom level page width.
Would this be possible?

Regards,
Bodo

**Comment by solewniczak** [comment]
refer: https://www.dokuwiki.org/plugin:pdfjs

**Comment by BodoBiker** [comment]
Hi,
thank you very much for the implementation of this enhancement. Great!

Regards,
Bodo
